loading annotations into memory...
Done (t=25.84s)
creating index...
index created!
Train Image Count: 280741
Train Class Count: 2
  0. BG
  1. building
loading annotations into memory...
Done (t=6.16s)
creating index...
index created!
Val Image Count: 60317
Val Class Count: 2
  0. BG
  1. building
logs/2024-10-22_09-28-25/maskrcnn_resnet50_fpn_v2.pth
/home/your_email/iptu/samples/mapping/main.py:241: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler() if device.type == 'cuda' and use_scaler else None
Epochs:   0%|                                                                                                  | 0/2 [00:00<?, ?it/s]
GPU disponível. Treinamento iniciará na GPU.
Traceback (most recent call last):                                                                         | 0/70186 [00:00<?, ?it/s]
  File "/home/your_email/iptu/samples/mapping/main.py", line 345, in <module>
    main(dataset_dir=args.dataset_dir, epochs=args.epochs, size=args.size, class_names=class_names)
  File "/home/your_email/iptu/samples/mapping/main.py", line 323, in main
    train_loop(model=model,
  File "/home/your_email/iptu/samples/mapping/main.py", line 247, in train_loop
    train_loss = run_epoch(model, train_dataloader, optimizer, lr_scheduler, device, scaler, epoch, is_training=True)
  File "/home/your_email/iptu/samples/mapping/main.py", line 160, in run_epoch
    for batch_id, (inputs, targets) in enumerate(dataloader):
  File "/home/your_email/miniconda/envs/iptu310/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/home/your_email/miniconda/envs/iptu310/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "/home/your_email/miniconda/envs/iptu310/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/your_email/miniconda/envs/iptu310/lib/python3.10/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/your_email/miniconda/envs/iptu310/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/your_email/miniconda/envs/iptu310/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/your_email/miniconda/envs/iptu310/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/your_email/iptu/samples/mapping/dataloader.py", line 30, in __getitem__
    image, targets = self._load_image_and_target(image_id)
  File "/home/your_email/iptu/samples/mapping/dataloader.py", line 65, in _load_image_and_target
    boxes = [self._extract_bbox(mask) for mask in masks.transpose(2, 0, 1)]
  File "/home/your_email/iptu/samples/mapping/dataloader.py", line 65, in <listcomp>
    boxes = [self._extract_bbox(mask) for mask in masks.transpose(2, 0, 1)]
  File "/home/your_email/iptu/samples/mapping/dataloader.py", line 77, in _extract_bbox
    xmin = np.min(positions[1])
  File "/home/your_email/miniconda/envs/iptu310/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2953, in min
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/your_email/miniconda/envs/iptu310/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
